version: '3.7'

services:
  nodejs:
    build: nodejs
    volumes:
      - ..:/usr/src/app
      - ./data/shell_history:/home/node/shell_history
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      HISTFILE: /home/node/shell_history/.x_history
    # command: npm install
    # command: /usr/src/app/entrypoint.sh
    command: >
      ash -c "npm install &&
      npm run start:dev"