version: '3.7'

services:
  nodejs:
    build: nodejs
    volumes:
      - ..:/usr/src/app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      PORT: 3000
    command: >
      ash -c "npm install &&
      npm run start:dev"