version: '3.7'

networks:
  building_net:
    driver: bridge

services:

  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENT_STORE_PORT=1113
    networks:
      - building_net

  nodejs:
    build: nodejs
    volumes:
      - ..:/usr/src/app
      - ./data/shell_history:/home/node/shell_history
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      HISTFILE: /home/node/shell_history/.x_history
    # command: npm install
    # command: /usr/src/app/entrypoint.sh
    command: >
      ash -c "npm install &&
      npm run start:dev"
    networks:
      - building_net
    depends_on:
      - eventstore
    links:
      - eventstore