version: '3.7'

networks:
  building_net:
    driver: bridge

volumes:
  vol_eventstore: {}
  db-data: {}
  mongo-config: {}

services:

  mongo-express:
    image: mongo-express
    #restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - building_net
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    ports:
      - 27017:27017
    networks:
      - building_net

  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    volumes:
      - vol_eventstore:/var/lib/eventstore
    #environment:
      #- EVENTSTORE_RUN_PROJECTIONS=All
      #- EVENTSTORE_START_STANDARD_PROJECTIONS=true
      #- EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2113/
    networks:
      - building_net

  nodejs:
    build: nodejs
    volumes:
      - ..:/usr/src/app
      - ./data/shell_history:/home/node/shell_history
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      HISTFILE: /home/node/shell_history/.x_history
    # command: npm install
    # command: /usr/src/app/entrypoint.sh
    command: >
      ash -c "npm install &&
      npm run start:dev"
    networks:
      - building_net
    depends_on:
      - eventstore
    links:
      - eventstore
